#!/bin/bash

if [ -z "$1" ]
  then
    echo "No argument(s) supplied. Please specify game session you want to join or make."
  else
    #./run chess -s chess.mst-ai.xyz -r "$@"
    TERM=xterm dotnet run chess -s chess.mst-ai.xyz --session "$@"
fi
